name: Build picohttpd for Rocky Linux/RHEL/CentOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub Actions runs Ubuntu, but Go produces Linux-compatible binary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Verify source
        run: |
          echo "Repository root files:"
          ls -lh
          if [ ! -f picohttpd.go ]; then
            echo "Error: picohttpd.go not found!"
            exit 1
          fi

      - name: Build Linux x86_64 binary
        run: |
          set -e
          
          # Remove old build folder to ensure fresh binary
          rm -rf build
          mkdir -p build
          
          # Build binary for Linux x86_64 (Rocky Linux, RHEL, CentOS)
          export GO111MODULE=off
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -extldflags '-static'" -o build/picohttpd picohttpd.go

          # Check binary info
          file build/picohttpd
          ls -lh build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: picohttpd-binary
          path: build/picohttpd
