name: Build picohttpd for Rocky Linux/RHEL/CentOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub Actions runs Ubuntu, but Go produces Linux-compatible binary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify picohttpd.go exists
        run: |
          echo "Repository root contents:"
          ls -lh
          if [ ! -f picohttpd.go ]; then
            echo "Error: picohttpd.go not found in repo root!"
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Go environment
        run: |
          echo "Go toolchain details:"
          go version
          go env

      - name: Build Linux x86_64 binary
        run: |
          set -e  # stop if any command fails
          echo "Starting build process..."
          
          # Clean and recreate old build folder to ensure fresh binary
          rm -rf build
          mkdir -p build

          # Force module mode off (we don't use go.mod)
          export GO111MODULE=off
          
          # Build fully static binary for Linux x86_64 (Rocky Linux, RHEL, CentOS)
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -extldflags '-static'" -o build/picohttpd picohttpd.go

          echo "Build completed. Contents of build/:"
          ls -lh build/

          echo "Binary details:"
          file build/picohttpd

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: picohttpd ${{ github.event.inputs.version }}
          files: build/picohttpd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
